create table if not exists public.timeline_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  projects jsonb not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.timeline_data enable row level security;

drop policy if exists "Users can read their own timeline" on public.timeline_data;
create policy "Users can read their own timeline"
on public.timeline_data for select
using (auth.uid() = user_id);

drop policy if exists "Users can create their own timeline" on public.timeline_data;
create policy "Users can create their own timeline"
on public.timeline_data for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own timeline" on public.timeline_data;
create policy "Users can update their own timeline"
on public.timeline_data for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own timeline" on public.timeline_data;
create policy "Users can delete their own timeline"
on public.timeline_data for delete
using (auth.uid() = user_id);

create table if not exists public.timeline_projects (
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id text not null,
  project jsonb not null,
  version bigint not null default 1 check (version > 0),
  deleted boolean not null default false,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  primary key (user_id, project_id),
  constraint timeline_projects_project_object check (jsonb_typeof(project) = 'object')
);

create index if not exists timeline_projects_user_updated_idx
  on public.timeline_projects (user_id, updated_at desc);

alter table public.timeline_projects enable row level security;

drop policy if exists "Users can read their own versioned projects" on public.timeline_projects;
create policy "Users can read their own versioned projects"
on public.timeline_projects for select
using (auth.uid() = user_id);

create table if not exists public.timeline_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  projects jsonb not null,
  reason text not null default 'auto',
  created_at timestamptz not null default now(),
  constraint timeline_snapshots_projects_array check (jsonb_typeof(projects) = 'array')
);

create index if not exists timeline_snapshots_user_created_idx
  on public.timeline_snapshots (user_id, created_at desc);

alter table public.timeline_snapshots enable row level security;

drop policy if exists "Users can read their own snapshots" on public.timeline_snapshots;
create policy "Users can read their own snapshots"
on public.timeline_snapshots for select
using (auth.uid() = user_id);

create or replace function public.sync_timeline_project(
  p_project_id text,
  p_project jsonb,
  p_base_version bigint default 0,
  p_deleted boolean default false
)
returns table (
  status text,
  project_id text,
  project jsonb,
  version bigint,
  deleted boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_current public.timeline_projects%rowtype;
  v_next_project jsonb;
  v_row_count integer := 0;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if coalesce(trim(p_project_id), '') = '' then
    raise exception 'Project id is required' using errcode = '22023';
  end if;
  if p_base_version < 0 then
    raise exception 'Base version must be zero or greater' using errcode = '22023';
  end if;
  if not p_deleted and (
    p_project is null
    or jsonb_typeof(p_project) <> 'object'
    or coalesce(p_project ->> 'id', '') <> p_project_id
  ) then
    raise exception 'Project payload is invalid' using errcode = '22023';
  end if;

  select tp.* into v_current
  from public.timeline_projects as tp
  where tp.user_id = v_user_id and tp.project_id = p_project_id
  for update;

  if not found then
    if p_base_version <> 0 then
      return query select 'conflict'::text, p_project_id, null::jsonb, 0::bigint, true, now();
      return;
    end if;

    v_next_project := coalesce(p_project, jsonb_build_object('id', p_project_id));
    insert into public.timeline_projects (user_id, project_id, project, version, deleted)
    values (v_user_id, p_project_id, v_next_project, 1, p_deleted)
    on conflict do nothing;
    get diagnostics v_row_count = row_count;

    if v_row_count = 0 then
      select tp.* into v_current
      from public.timeline_projects as tp
      where tp.user_id = v_user_id and tp.project_id = p_project_id;
      return query select 'conflict'::text, v_current.project_id, v_current.project,
        v_current.version, v_current.deleted, v_current.updated_at;
      return;
    end if;

    return query
    select 'applied'::text, tp.project_id, tp.project, tp.version, tp.deleted, tp.updated_at
    from public.timeline_projects as tp
    where tp.user_id = v_user_id and tp.project_id = p_project_id;
    return;
  end if;

  if v_current.version <> p_base_version then
    return query select 'conflict'::text, v_current.project_id, v_current.project,
      v_current.version, v_current.deleted, v_current.updated_at;
    return;
  end if;

  v_next_project := coalesce(p_project, v_current.project);
  update public.timeline_projects as tp
  set project = v_next_project,
      version = tp.version + 1,
      deleted = p_deleted,
      updated_at = now()
  where tp.user_id = v_user_id and tp.project_id = p_project_id
  returning tp.* into v_current;

  return query select 'applied'::text, v_current.project_id, v_current.project,
    v_current.version, v_current.deleted, v_current.updated_at;
end;
$$;

create or replace function public.create_timeline_snapshot(p_reason text default 'auto')
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_projects jsonb;
  v_last_id bigint;
  v_last_projects jsonb;
  v_snapshot_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select coalesce(jsonb_agg(source.project order by source.project_id), '[]'::jsonb)
  into v_projects
  from (
    select tp.project_id, tp.project
    from public.timeline_projects as tp
    where tp.user_id = v_user_id and not tp.deleted
  ) as source;

  select ts.id, ts.projects into v_last_id, v_last_projects
  from public.timeline_snapshots as ts
  where ts.user_id = v_user_id
  order by ts.created_at desc, ts.id desc
  limit 1;

  if v_last_id is not null and v_last_projects = v_projects then
    return v_last_id;
  end if;

  insert into public.timeline_snapshots (user_id, projects, reason)
  values (v_user_id, v_projects, left(coalesce(nullif(trim(p_reason), ''), 'auto'), 40))
  returning id into v_snapshot_id;

  delete from public.timeline_snapshots as ts
  where ts.user_id = v_user_id
    and ts.id in (
      select old.id
      from public.timeline_snapshots as old
      where old.user_id = v_user_id
      order by old.created_at desc, old.id desc
      offset 50
    );

  return v_snapshot_id;
end;
$$;

create or replace function public.bootstrap_timeline_projects(p_projects jsonb)
returns setof public.timeline_projects
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_project jsonb;
  v_project_id text;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_projects is null or jsonb_typeof(p_projects) <> 'array' then
    raise exception 'Projects must be an array' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.timeline_projects as tp where tp.user_id = v_user_id
  ) then
    for v_project in select value from jsonb_array_elements(p_projects)
    loop
      v_project_id := coalesce(v_project ->> 'id', '');
      if v_project_id <> '' and jsonb_typeof(v_project) = 'object' then
        insert into public.timeline_projects (user_id, project_id, project, version, deleted)
        values (v_user_id, v_project_id, v_project, 1, false)
        on conflict do nothing;
      end if;
    end loop;
    perform public.create_timeline_snapshot('migration');
  end if;

  return query
  select tp.* from public.timeline_projects as tp
  where tp.user_id = v_user_id
  order by tp.project_id;
end;
$$;

create or replace function public.restore_timeline_snapshot(p_snapshot_id bigint)
returns setof public.timeline_projects
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_projects jsonb;
  v_project jsonb;
  v_project_id text;
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select ts.projects into v_projects
  from public.timeline_snapshots as ts
  where ts.id = p_snapshot_id and ts.user_id = v_user_id;

  if v_projects is null then
    raise exception 'Snapshot not found' using errcode = 'P0002';
  end if;

  perform 1 from public.timeline_projects as tp
  where tp.user_id = v_user_id
  for update;

  update public.timeline_projects as tp
  set deleted = true,
      version = tp.version + 1,
      updated_at = now()
  where tp.user_id = v_user_id
    and not tp.deleted
    and not exists (
      select 1 from jsonb_array_elements(v_projects) as item
      where item ->> 'id' = tp.project_id
    );

  for v_project in select value from jsonb_array_elements(v_projects)
  loop
    v_project_id := coalesce(v_project ->> 'id', '');
    if v_project_id <> '' and jsonb_typeof(v_project) = 'object' then
      insert into public.timeline_projects (user_id, project_id, project, version, deleted)
      values (v_user_id, v_project_id, v_project, 1, false)
      on conflict (user_id, project_id) do update
      set project = excluded.project,
          version = public.timeline_projects.version + 1,
          deleted = false,
          updated_at = now();
    end if;
  end loop;

  perform public.create_timeline_snapshot('restore');

  return query
  select tp.* from public.timeline_projects as tp
  where tp.user_id = v_user_id
  order by tp.project_id;
end;
$$;

revoke all on public.timeline_projects from anon;
revoke all on public.timeline_snapshots from anon;
grant select on public.timeline_projects to authenticated;
grant select on public.timeline_snapshots to authenticated;
grant usage, select on sequence public.timeline_snapshots_id_seq to authenticated;

revoke all on function public.sync_timeline_project(text, jsonb, bigint, boolean) from public, anon;
revoke all on function public.create_timeline_snapshot(text) from public, anon;
revoke all on function public.bootstrap_timeline_projects(jsonb) from public, anon;
revoke all on function public.restore_timeline_snapshot(bigint) from public, anon;
grant execute on function public.sync_timeline_project(text, jsonb, bigint, boolean) to authenticated;
grant execute on function public.create_timeline_snapshot(text) to authenticated;
grant execute on function public.bootstrap_timeline_projects(jsonb) to authenticated;
grant execute on function public.restore_timeline_snapshot(bigint) to authenticated;

insert into public.timeline_projects (user_id, project_id, project, version, deleted, updated_at, created_at)
select td.user_id,
       item ->> 'id',
       item,
       1,
       false,
       td.updated_at,
       td.created_at
from public.timeline_data as td
cross join lateral jsonb_array_elements(td.projects) as item
where jsonb_typeof(td.projects) = 'array'
  and jsonb_typeof(item) = 'object'
  and coalesce(item ->> 'id', '') <> ''
on conflict (user_id, project_id) do nothing;

insert into public.timeline_snapshots (user_id, projects, reason, created_at)
select td.user_id, td.projects, 'migration', td.updated_at
from public.timeline_data as td
where jsonb_typeof(td.projects) = 'array'
  and not exists (
    select 1 from public.timeline_snapshots as ts where ts.user_id = td.user_id
  );
